### ISSUE TITLE
An issue with the practice packs

### ISSUE THREAD

**Issue by LeMikusito** [Minemaker0430/GDDPIntegration#18]
The problem is that i want to enter to a practice pack of GDDP integration, the game just crashes

![Captura de pantalla 2024-05-27 222336](https://github.com/Minemaker0430/GDDPIntegration/assets/171000213/a8287c1c-7288-4ac3-9a84-717ac4c064e6)
[2024-05-27_22-23-13.log](https://github.com/Minemaker0430/GDDPIntegration/files/15463899/2024-05-27_22-23-13.log)
 And this was not happening before i updated the mod at may 27th 2024
so, i apreciate if you can fix this, because i really like this mod, thanks!

**Comment by Minemaker0430** [comment]
Will look into it

**Comment by Minemaker0430** [comment]
I can't get it to crash myself, would you mind sending me your save file?
Should be `C:\Users\<username>\AppData\Local\GeometryDash\geode\mods\minemaker0430.gddp_integration\saved.json`

**Comment by LeMikusito** [comment]
sure, i think that is this
[saved.json](https://github.com/Minemaker0430/GDDPIntegration/files/15477522/saved.json)

**Comment by Minemaker0430** [comment]
I still wasn't able to recreate the crash with your save unfortunately, I will continue to investigate but it might be a while until a fix is published due to 2.206 coming out

In the meantime, all "Practice Packs" can be found on the GDDPOfficial GD Account as Startpos lists if you need to practice
